variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'webapigateway'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'apiwebrepository'
  serviceName: 'prdrwdwebwa1409'
